name: Build and Deploy to Azure Web App

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Show Azure Account
      run: az account show

    - name: List ACR Repositories
      run: az acr repository list --name chatbotacr38237 || echo "No repo"

    - name: Log in to Azure Container Registry
      run: |
        az acr login --name chatbotacr38237

    - name: Build and push Docker image
      run: |
        docker build -t chatbotacr38237.azurecr.io/chatbot-web-app:${{ github.sha }} .
        docker push chatbotacr38237.azurecr.io/chatbot-web-app:${{ github.sha }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: chatbot-web-app
        images: chatbotacr38237.azurecr.io/chatbot-web-app:${{ github.sha }}

